# Generated by Django 5.2.x

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255)),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF / VAT Number')),
                ('tamano_empresa', models.CharField(blank=True, choices=[('micro', 'Microempresa'), ('pequena', 'Pequeña'), ('mediana', 'Mediana'), ('grande', 'Grande')], max_length=20)),
                ('industria', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('finanzas', 'Finanzas'), ('educacion', 'Educación'), ('comercio', 'Comercio'), ('otros', 'Otros')], max_length=50)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('sitio_web', models.URLField(blank=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_primer_contacto', models.DateField(blank=True, null=True)),
                ('fecha_firma_contrato', models.DateField(blank=True, null=True)),
                ('estado_cliente', models.CharField(choices=[('prospecto', 'Prospecto'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='prospecto', max_length=20)),
                ('herramienta', models.CharField(blank=True, help_text='Herramienta utilizada (opcional)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('completada', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('actols', 'Actols'), ('andres', 'Andrés'), ('camilo', 'Camilo')], max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, verbose_name='URL del proyecto')),
                ('repo_url', models.URLField(blank=True, verbose_name='URL del repositorio')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Contrato (PDF)')),
                ('proceso', models.CharField(choices=[('activo', 'Activo'), ('terminado', 'Terminado'), ('entregado', 'Entregado'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('facturacion_estado', models.CharField(choices=[('por_pagar', 'Por pagar'), ('pagado', 'Pagado'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20)),
                ('facturacion_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='core.cliente')),
            ],
        ),
    ]
